# Generated by Django 2.2.5 on 2020-11-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roses', '0002_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
