"""empty message

Revision ID: 5d2244560201
Revises: e0946d801d38
Create Date: 2020-11-19 11:26:58.574088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2244560201'
down_revision = 'e0946d801d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('per_share_deal_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('executive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commpany', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('first_year_non_recurring_compensation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['commpany'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compensation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('compensation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['executive'], ['executive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('non_equity_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('reasonable_compensation_before_change', sa.Boolean(), nullable=True),
    sa.Column('reasonable_compensation_after_change', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['executive'], ['executive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive', sa.Integer(), nullable=True),
    sa.Column('number', sa.Float(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('vesting_date', sa.Date(), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('change_of_control', sa.Boolean(), nullable=True),
    sa.Column('accelerated', sa.Boolean(), nullable=True),
    sa.Column('roll_over', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['executive'], ['executive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('companies')
    op.drop_table('options')
    op.drop_table('non_equity_payments')
    op.drop_table('executives')
    op.drop_table('base_amounts')
    op.drop_constraint(None, 'restricted_stock', type_='foreignkey')
    op.create_foreign_key(None, 'restricted_stock', 'executive', ['executive'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restricted_stock', type_='foreignkey')
    op.create_foreign_key(None, 'restricted_stock', 'executives', ['executive'], ['id'])
    op.create_table('base_amounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('executive', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('year_5_compensation', sa.FLOAT(), nullable=True),
    sa.Column('year_4_compensation', sa.FLOAT(), nullable=True),
    sa.Column('year_3_compensation', sa.FLOAT(), nullable=True),
    sa.Column('year_2_compensation', sa.FLOAT(), nullable=True),
    sa.Column('year_1_compensation', sa.FLOAT(), nullable=True),
    sa.Column('year_1_special_compensation', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['executive'], ['executives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('executives',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('commpany', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=32), nullable=True),
    sa.Column('title', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['commpany'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('non_equity_payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('executive', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('description', sa.VARCHAR(length=64), nullable=True),
    sa.Column('reasonable_compensation_before_change', sa.BOOLEAN(), nullable=True),
    sa.Column('reasonable_compensation_after_change', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('reasonable_compensation_after_change IN (0, 1)'),
    sa.CheckConstraint('reasonable_compensation_before_change IN (0, 1)'),
    sa.ForeignKeyConstraint(['executive'], ['executives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('executive', sa.INTEGER(), nullable=True),
    sa.Column('number', sa.FLOAT(), nullable=True),
    sa.Column('grant_date', sa.DATE(), nullable=True),
    sa.Column('vesting_date', sa.DATE(), nullable=True),
    sa.Column('strike_price', sa.FLOAT(), nullable=True),
    sa.Column('change_of_control', sa.BOOLEAN(), nullable=True),
    sa.Column('accelerated', sa.BOOLEAN(), nullable=True),
    sa.Column('roll_over', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('accelerated IN (0, 1)'),
    sa.CheckConstraint('change_of_control IN (0, 1)'),
    sa.CheckConstraint('roll_over IN (0, 1)'),
    sa.ForeignKeyConstraint(['executive'], ['executives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('transaction_date', sa.DATE(), nullable=True),
    sa.Column('per_share_deal_price', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('option')
    op.drop_table('non_equity_payment')
    op.drop_table('compensation')
    op.drop_table('executive')
    op.drop_table('company')
    # ### end Alembic commands ###
