"""empty message

Revision ID: e0946d801d38
Revises: 
Create Date: 2020-11-18 15:18:06.037020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0946d801d38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('per_share_deal_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('executives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commpany', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['commpany'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_amounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('year_5_compensation', sa.Float(), nullable=True),
    sa.Column('year_4_compensation', sa.Float(), nullable=True),
    sa.Column('year_3_compensation', sa.Float(), nullable=True),
    sa.Column('year_2_compensation', sa.Float(), nullable=True),
    sa.Column('year_1_compensation', sa.Float(), nullable=True),
    sa.Column('year_1_special_compensation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['executive'], ['executives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('non_equity_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('reasonable_compensation_before_change', sa.Boolean(), nullable=True),
    sa.Column('reasonable_compensation_after_change', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['executive'], ['executives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive', sa.Integer(), nullable=True),
    sa.Column('number', sa.Float(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('vesting_date', sa.Date(), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('change_of_control', sa.Boolean(), nullable=True),
    sa.Column('accelerated', sa.Boolean(), nullable=True),
    sa.Column('roll_over', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['executive'], ['executives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restricted_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive', sa.Integer(), nullable=True),
    sa.Column('number', sa.Float(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('vesting_date', sa.Date(), nullable=True),
    sa.Column('change_of_control', sa.Boolean(), nullable=True),
    sa.Column('accelerated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['executive'], ['executives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restricted_stock')
    op.drop_table('options')
    op.drop_table('non_equity_payments')
    op.drop_table('base_amounts')
    op.drop_table('executives')
    op.drop_table('companies')
    # ### end Alembic commands ###
