"""Initial migration after restarting database

Revision ID: ee5558410924
Revises: 
Create Date: 2020-11-20 12:17:50.521222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee5558410924'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('per_share_deal_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('executive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commpany_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('first_year_non_recurring_compensation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['commpany_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compensation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('compensation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['executive_id'], ['executive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('non_equity_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('reasonable_compensation_before_change', sa.Boolean(), nullable=True),
    sa.Column('reasonable_compensation_after_change', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['executive_id'], ['executive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Float(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('vesting_date', sa.Date(), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('change_of_control', sa.Boolean(), nullable=True),
    sa.Column('accelerated', sa.Boolean(), nullable=True),
    sa.Column('roll_over', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['executive_id'], ['executive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restricted_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('executive_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Float(), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('vesting_date', sa.Date(), nullable=True),
    sa.Column('change_of_control', sa.Boolean(), nullable=True),
    sa.Column('accelerated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['executive_id'], ['executive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restricted_stock')
    op.drop_table('option')
    op.drop_table('non_equity_payment')
    op.drop_table('compensation')
    op.drop_table('executive')
    op.drop_table('company')
    # ### end Alembic commands ###
