"""empty message

Revision ID: 5b293ecd5b0e
Revises: bba42e7171bc
Create Date: 2021-03-06 14:20:12.193184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b293ecd5b0e'
down_revision = 'bba42e7171bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('favorited_id', sa.Integer(), nullable=False),
    sa.Column('favorited_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorited_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['favorited_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('favorited_id', 'favorited_by_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    # ### end Alembic commands ###
